#!/bin/sh

set -e

case "$1" in
    remove|upgrade|deconfigure)
	update-alternatives --remove flash-mozilla.so /usr/lib/freshplayerplugin/libfreshwrapper-pepperflash.so || true
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0


